apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  labels:
    app: p3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p3-app
  template:
    metadata:
      labels:
        app: p3-app
    spec:
      containers:
      - name: p3-app
        image: wil42/playground:v3
        ports:
        - containerPort: 8888
